KUSITMS-27th-TEAM3/BackEnd

.github/workflows/cd.yml

---
기존에 aws 서버 안에서 docker-compose.yml파일 관리에서 github action을 통해 파일 생성 관리로 변경
---
---

[fix] docker-compose.yml 파일 github action으로 관리

---

.github/workflows/ci.yml
build.gradle
src/docs/asciidoc/index.adoc
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/SamsionApplicationTests.java
src/test/java/com/kusitms/samsion/config/CommonRestDocs.java
src/test/java/com/kusitms/samsion/config/RestDocsConfig.java

--- RestDocs 사용하기 위한 기본 설정
---
---

[feat] RestDocs 세팅

---

build.gradle
src/main/java/com/kusitms/samsion/application/album/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/application/album/service/AlbumCreateService.java
src/main/java/com/kusitms/samsion/application/user/service/MyPetUpdateService.java
src/main/java/com/kusitms/samsion/common/exception/Error.java
src/main/java/com/kusitms/samsion/domain/album/exception/FileDeleteException.java
src/main/java/com/kusitms/samsion/domain/album/exception/FileExtentionException.java
src/main/java/com/kusitms/samsion/domain/album/exception/FileUploadException.java
src/main/java/com/kusitms/samsion/infrastructure/s3/S3Config.java
src/main/java/com/kusitms/samsion/infrastructure/s3/S3DeleteService.java
src/main/java/com/kusitms/samsion/infrastructure/s3/S3UploadService.java

- 이미지 업로드 기능 구현
- 삭제 기능은 service만 구현해둠
- #13
---

[feat] 이미지 업로드 기능

---

src/main/java/com/kusitms/samsion/application/album/mapper/AlbumImageMapper.java
src/main/java/com/kusitms/samsion/application/album/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/application/album/service/AlbumCreateService.java
src/main/java/com/kusitms/samsion/application/album/service/AlbumReadService.java
src/main/java/com/kusitms/samsion/application/user/dto/request/UserSignUpRequest.java
src/main/java/com/kusitms/samsion/application/user/handler/UserSignUpHandler.java
src/main/java/com/kusitms/samsion/application/user/mapper/MyPetMapper.java
src/main/java/com/kusitms/samsion/application/user/mapper/UserMapper.java
src/main/java/com/kusitms/samsion/application/user/service/MyPetInfoService.java
src/main/java/com/kusitms/samsion/application/user/service/MyPetUpdateService.java
src/main/java/com/kusitms/samsion/common/annotation/Mapper.java
src/main/java/com/kusitms/samsion/common/exception/handler/GlobalExceptionHandler.java
src/main/java/com/kusitms/samsion/common/util/UserUtils.java
src/main/java/com/kusitms/samsion/domain/album/service/AlbumImageSaveService.java
src/main/java/com/kusitms/samsion/domain/user/service/UserQueryService.java
src/main/java/com/kusitms/samsion/presentation/album/AlbumController.java
src/test/java/com/kusitms/samsion/application/user/handler/UserSignUpHandlerTest.java
src/test/java/com/kusitms/samsion/application/user/service/MyPetInfoServiceTest.java
src/test/java/com/kusitms/samsion/application/user/service/MyPetUpdateServiceTest.java
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/UserTestUtils.java
src/test/java/com/kusitms/samsion/domain/user/service/UserGetServiceTest.java
src/test/java/com/kusitms/samsion/domain/user/service/UserQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/user/service/UserSaveServiceTest.java

---
* User 관련 서비스 테스트 코드 작성
* 테스트 유틸 추가
* 테스트 상수 추가
* Mapper 클래스 컴포넌트 등록하지 않게 바꿈 -> 빈등록하지 않아도 되보여서 바꿨어
* 예외 처리해주는 controller advice 추가
---
---

[test] User Service 테스트 코드 작성

---

src/docs/asciidoc/Comment-API.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/kusitms/samsion/application/comment/dto/request/CommentCreateRequest.java
src/main/java/com/kusitms/samsion/application/comment/dto/response/CommentInfoResponse.java
src/main/java/com/kusitms/samsion/application/comment/mapper/CommentMapper.java
src/main/java/com/kusitms/samsion/application/comment/service/CommentCreateService.java
src/main/java/com/kusitms/samsion/application/comment/service/CommentUpdateService.java
src/main/java/com/kusitms/samsion/common/exception/Error.java
src/main/java/com/kusitms/samsion/domain/album/entity/Album.java
src/main/java/com/kusitms/samsion/domain/comment/entity/Comment.java
src/main/java/com/kusitms/samsion/domain/comment/exception/CommentException.java
src/main/java/com/kusitms/samsion/domain/comment/exception/CommentNotFoundException.java
src/main/java/com/kusitms/samsion/domain/comment/repository/CommentRepository.java
src/main/java/com/kusitms/samsion/domain/comment/service/CommentQueryService.java
src/main/java/com/kusitms/samsion/domain/comment/service/CommentSaveService.java
src/main/java/com/kusitms/samsion/presentation/comment/CommentController.java
src/main/resources/static/docs/Comment-API.html
src/test/java/com/kusitms/samsion/common/util/AlbumTestUtils.java
src/test/java/com/kusitms/samsion/common/util/CommentTestUtils.java
src/test/java/com/kusitms/samsion/domain/comment/service/CommentQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/comment/service/CommentSaveServiceTest.java
src/test/java/com/kusitms/samsion/domain/empathy/service/EmpathyDeleteServiceTest.java
src/test/java/com/kusitms/samsion/domain/empathy/service/EmpathyQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/empathy/service/EmpathySaveServiceTest.java
src/test/java/com/kusitms/samsion/presentation/comment/CommentControllerTest.java

- 댓글 생성 및 수정 기능 
- 관련 테스트 코드 작성 (application service 쪽은 아직 작성 못함)
---
---

[feat] 댓글 생성/수정 기능 추가 및 관련 클래스 테스트 코드 추가 

---

build.gradle
src/docs/asciidoc/Comment-API.adoc
src/docs/asciidoc/Empathy-API.adoc
src/docs/asciidoc/Question-API.adoc
src/docs/asciidoc/User-API.adoc
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html

- RestDocs 문서 경로 못 찾는 문제 해결 및 문서 수정 
---
---

[refactor] RestDocs 설정 변경 및 문서 수정

---

src/main/java/com/kusitms/samsion/common/config/CorsConfig.java

[fix] cors 설정 변경

---

src/main/java/com/kusitms/samsion/domain/question/domain/repository/QuestionRepository.java
src/main/java/com/kusitms/samsion/domain/question/domain/service/QuestionQueryService.java
src/test/java/com/kusitms/samsion/domain/question/domain/service/QuestionQueryServiceTest.java

---
* @query 사용하지 않게 변경
---
---

[fix] findAll jpql 사용하지 않게 변경

---

src/main/java/com/kusitms/samsion/common/consts/IgnoredPathConst.java
src/main/java/com/kusitms/samsion/common/security/oauth/OAuth2SuccessHandler.java
src/main/java/com/kusitms/samsion/domain/auth/presentation/AuthController.java

---
* oauth2 로그인 성공시 path param으로 토큰 정보 넘겨줌
---
---

[fix] oauth2 로그인 성공시 path param으로 토큰 정보 넘겨줌

---

src/main/java/com/kusitms/samsion/common/security/oauth/OAuth2SuccessHandler.java

[fix] oauth2 로그인 성공시 redirect url 변경

---

src/main/java/com/kusitms/samsion/common/infrastructure/s3/S3UploadService.java
src/main/java/com/kusitms/samsion/common/security/oauth/OAuth2SuccessHandler.java
src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/user/application/dto/response/MyPetResponse.java
src/main/java/com/kusitms/samsion/domain/user/application/mapper/MyPetMapper.java
src/main/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/MyPet.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/User.java
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/UserTestUtils.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetInfoUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/user/presentation/UserControllerTest.java

---
* MyPet 나이, 품종 필드 추가
* 사용자 테스트 수정(조회, 수정)
* import 수정 및 미사용 메서드 주석 처리
---
---

[feat] MyPet 나이, 품종 필드 추가

---

src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumCreateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/response/AlbumSimpleResponse.java
src/main/java/com/kusitms/samsion/domain/album/application/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/domain/album/domain/entity/Album.java

---
* 앨범 제목 필드 추가
* 생성, 응답에 제목 필드 추가
---
---

[feat] 앨범 제목 필드 추가

---

src/docs/asciidoc/Comment-API.adoc
src/main/java/com/kusitms/samsion/common/exception/Error.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentDeleteUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/domain/entity/Comment.java
src/main/java/com/kusitms/samsion/domain/comment/domain/exception/NotSameUserException.java
src/main/java/com/kusitms/samsion/domain/comment/domain/service/CommentDeleteService.java
src/main/java/com/kusitms/samsion/domain/comment/domain/service/CommentValidAccessService.java
src/main/java/com/kusitms/samsion/domain/comment/presentation/CommentController.java
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/UserTestUtils.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommentDeleteUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/comment/domain/service/CommentDeleteServiceTest.java
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java

- 댓글 삭제 usecase, controller 추가
- 댓글 수정 동일 유저 검증 로직 추가
- 테스트 코드 작성 (CommentValidAccessService 테스트 코드 작성해야 하나?) 
--- 
---

댓글 삭제, 수정 usecase 작성 및 테스트 코드 작성 

---

src/main/java/com/kusitms/samsion/common/slice/SliceResponse.java
src/main/java/com/kusitms/samsion/domain/question/application/service/QuestionReadUseCase.java
src/main/java/com/kusitms/samsion/domain/question/domain/repository/QuestionRepository.java
src/main/java/com/kusitms/samsion/domain/question/domain/service/QuestionQueryService.java
src/main/java/com/kusitms/samsion/domain/question/presentation/QuestionController.java
src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/user/application/dto/response/MyPetResponse.java
src/main/java/com/kusitms/samsion/domain/user/application/mapper/MyPetMapper.java
src/main/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/MyPet.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/User.java
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/SliceTestUtils.java
src/test/java/com/kusitms/samsion/common/util/UserTestUtils.java
src/test/java/com/kusitms/samsion/domain/question/application/service/QuestionReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/question/domain/service/QuestionQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/question/presentation/QuestionControllerTest.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetInfoUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/user/presentation/UserControllerTest.java

---
* MyPet 클래스에 petNickname 필드 추가하고 수정, 조회 json에 petNickname 추가
* 질문 조회에서 PageResponse가 아닌 SliceResponse로 변경
---
---

[feat] MyPet petNickname 필드 추가 및 테스트 수정

---

src/docs/asciidoc/Comment-API.adoc
src/docs/asciidoc/Overview.adoc
src/docs/asciidoc/Question-API.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/kusitms/samsion/domain/comment/application/dto/response/CommentInfoResponse.java
src/main/java/com/kusitms/samsion/domain/comment/application/mapper/CommentMapper.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentReadUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/domain/repository/CommentRepository.java
src/main/java/com/kusitms/samsion/domain/comment/domain/service/CommentQueryService.java
src/main/java/com/kusitms/samsion/domain/comment/presentation/CommentController.java
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/common/util/CommentTestUtils.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommetReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java

- 댓글 조회 무한스크롤로 구현
- 관련 usecase 테스트 코드 작성
- 관련 controller 테스트 코드, RestDocs 문서 작성
- 에러 코드 RestDocs 문서 작성 
---
---

[feat] 댓글 조회 API 구현 및 테스트 코드, 문서 작성

---

src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html

[docs] RestDocs html 수정

---

src/main/java/com/kusitms/samsion/common/infrastructure/s3/S3UploadService.java

[feat] 파일 확장자 추가

---

src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCaseTest.java

[fix] petAge String 입력후 int로 변환

---

src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumImageUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/request/TagUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/response/AlbumInfoResponse.java
src/main/java/com/kusitms/samsion/domain/album/application/handler/AlbumImageUpdateHandler.java
src/main/java/com/kusitms/samsion/domain/album/application/handler/TagUpdateHandler.java
src/main/java/com/kusitms/samsion/domain/album/application/mapper/AlbumImageMapper.java
src/main/java/com/kusitms/samsion/domain/album/application/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumReadUseCase.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/album/domain/entity/Album.java
src/main/java/com/kusitms/samsion/domain/album/domain/repository/AlbumImageRepository.java
src/main/java/com/kusitms/samsion/domain/album/domain/repository/TagRepository.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumImageDeleteService.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumImageUpdateService.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumQueryService.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumUpdateService.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/TagDeleteService.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/TagUpdateService.java
src/main/java/com/kusitms/samsion/domain/album/presentation/AlbumController.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCase.java
src/main/java/com/kusitms/samsion/domain/empathy/application/service/EmpathyToggleUseCase.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/empathy/application/service/EmpathyToggleUseCaseTest.java

---
* Album 수정 Api 추가
* AlbumQueryService에서의 select 쿼리 메서드 이름 변경 (getAlbumById -> findAlbumById)
---
---

[feat] 앨범 수정 기능 추가 및 쿼리 메서드 이름 변경

---

src/main/java/com/kusitms/samsion/domain/comment/presentation/CommentController.java
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java

[feat] 댓글 수정, 삭제 albumId 파라미터 추가

---

src/main/java/com/kusitms/samsion/domain/grid/application/dto/request/GridUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/grid/application/handler/GridUpdateHandler.java
src/main/java/com/kusitms/samsion/domain/grid/domain/entity/Grid.java
src/main/java/com/kusitms/samsion/domain/user/application/mapper/MyPetMapper.java
src/main/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCase.java
src/test/java/com/kusitms/samsion/domain/user/application/service/MyPetUpdateUseCaseTest.java

[feat] 사용자 팻 이미지 수정시 Grid 이미지 변경 및 파라미터 오류 수정

---

src/main/java/com/kusitms/samsion/common/infrastructure/s3/S3UploadService.java

[feat] .svg 확장자 추가

---

src/docs/asciidoc/FuneralShop-API.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/kusitms/samsion/domain/funeralshop/application/dto/request/FuneralShopSearchRequest.java
src/main/java/com/kusitms/samsion/domain/funeralshop/application/dto/response/FuneralShopInfoResponse.java
src/main/java/com/kusitms/samsion/domain/funeralshop/application/mapper/FuneralShopMapper.java
src/main/java/com/kusitms/samsion/domain/funeralshop/application/service/FuneralShopReadUseCase.java
src/main/java/com/kusitms/samsion/domain/funeralshop/domain/entity/FuneralShop.java
src/main/java/com/kusitms/samsion/domain/funeralshop/domain/entity/RunType.java
src/main/java/com/kusitms/samsion/domain/funeralshop/domain/repository/FuneralShopRepository.java
src/main/java/com/kusitms/samsion/domain/funeralshop/domain/repository/FuneralShopRepositoryCustom.java
src/main/java/com/kusitms/samsion/domain/funeralshop/domain/service/FuneralShopQueryService.java
src/main/java/com/kusitms/samsion/domain/funeralshop/infrastructure/FuneralShopRepositoryImpl.java
src/main/java/com/kusitms/samsion/domain/funeralshop/presentation/FuneralShopController.java
src/main/resources/static/docs/Album-API.html
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Enum.html
src/main/resources/static/docs/FuneralShop-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/FuneralShopTestUtils.java
src/test/java/com/kusitms/samsion/domain/funeralshop/application/service/FuneralShopReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/funeralshop/domain/service/FuneralShopQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/funeralshop/presentation/FuneralShopControllerTest.java

- 장례 정보 조회 코드 작성
- 해당 테스트 코드 작성
- RestDocs 문서 작성
---
---

[feat] 장례 정보 조회 구현

---

src/main/java/com/kusitms/samsion/domain/funeralshop/domain/repository/FuneralShopRepository.java

[fix] FuneralShopRepository 의존성 문제 해결

---

src/main/java/com/kusitms/samsion/common/consts/IgnoredPathConst.java

[fix] 앨범 전체 조회, 장례정보 조회 요청시 인증 없이도 가능하도록 수정

---

src/main/java/com/kusitms/samsion/domain/funeralshop/infrastructure/FuneralShopRepositoryImpl.java

[feat] 전체 버튼 클릭 시 전체 데이터 보내주기

---

src/main/java/com/kusitms/samsion/common/security/jwt/JwtAuthenticationFilter.java

---
* ignoredpath에서 GET 요청만 인증없이 진행가능하도록 수정
---
---

[fix] 인증 요청에 대해 http method GET만 검사하도록 수정

---

src/main/java/com/kusitms/samsion/domain/album/application/dto/response/AlbumInfoResponse.java
src/main/java/com/kusitms/samsion/domain/album/application/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumReadUseCase.java
src/main/java/com/kusitms/samsion/domain/album/presentation/AlbumController.java
src/main/resources/static/docs/Album-API.html
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Enum.html
src/main/resources/static/docs/FuneralShop-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/album/application/service/AlbumReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/album/presentation/AlbumControllerTest.java

---
* 앨범 상세 조회시 접근 사용자 프로필이미지도 같이 반환
* 테스트 수정
* 앨범 명세 수정
---
---

[fix] 앨범 상세 조회시 접근 사용자 프로필이미지도 같이 반환

---

src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumCreateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumSearchRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/response/AlbumInfoResponse.java
src/main/java/com/kusitms/samsion/domain/album/application/handler/AlbumImageUpdateHandler.java
src/main/java/com/kusitms/samsion/domain/album/application/mapper/AlbumMapper.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumCreateUseCase.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumReadUseCase.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/album/presentation/AlbumController.java
src/main/java/com/kusitms/samsion/domain/comment/application/dto/response/CommentCountResponse.java
src/main/java/com/kusitms/samsion/domain/comment/application/dto/response/CommentInfoResponse.java
src/main/java/com/kusitms/samsion/domain/comment/application/mapper/CommentMapper.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentReadUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/comment/presentation/CommentController.java
src/main/java/com/kusitms/samsion/domain/empathy/application/dto/response/EmpathyCountResponse.java
src/main/java/com/kusitms/samsion/domain/empathy/application/mapper/EmpathyMapper.java
src/main/java/com/kusitms/samsion/domain/empathy/application/service/EmpathyCountUseCase.java
src/main/java/com/kusitms/samsion/domain/empathy/presentation/EmpathyController.java
src/main/resources/static/docs/Album-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/album/application/service/AlbumCreateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/album/application/service/AlbumReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/album/presentation/AlbumControllerTest.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommetReadUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java
src/test/java/com/kusitms/samsion/domain/empathy/presentation/EmpathyControllerTest.java

---
* 앨범 상세 정보 조회 API에서 더이상 댓글, 공감 수 반환하지 않음
* 공감 수 반환할때 공감 여부 반환
---
---

[refactor] 댓글 수, 공감 수 및 여부 반환 API 추가 및 수정 

---

src/docs/asciidoc/Comment-API.adoc
src/docs/asciidoc/Empathy-API.adoc
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java
src/test/java/com/kusitms/samsion/domain/empathy/presentation/EmpathyControllerTest.java

[docs] 공감, 댓글 명세 수정

---

src/main/resources/static/docs/Album-API.html
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/Enum.html
src/main/resources/static/docs/FuneralShop-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommentCreateUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/comment/application/service/CommentUpdateUseCaseTest.java

[refactor] 댓글 테스트 코드 수정

---

src/main/java/com/kusitms/samsion/common/infrastructure/s3/S3UploadService.java
src/main/java/com/kusitms/samsion/domain/album/application/dto/request/AlbumUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/album/domain/entity/AlbumImage.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumImageUpdateService.java

[Fix] 앨범 수정시 기존 url List, 추가 이미지 파일 List 가 null이여도 정상 처리되도록 수정

---

src/main/java/com/kusitms/samsion/domain/album/application/service/AlbumUpdateUseCase.java
src/main/java/com/kusitms/samsion/domain/album/domain/service/AlbumValidAccessService.java

[Fix] 앨범 수정시 앨범 작성자와 요청 사용자가 다르면 예외발생

---

src/main/java/com/kusitms/samsion/domain/comment/domain/entity/Comment.java

[refactor] soft delete 쿼리문 변경

---

src/main/java/com/kusitms/samsion/domain/comment/application/dto/response/CommentInfoResponse.java
src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentUpdateUseCase.java
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/domain/comment/presentation/CommentControllerTest.java

[refactor] 댓글 수정 코드, 문서 수정

---

src/main/java/com/kusitms/samsion/domain/comment/application/mapper/CommentMapper.java

[refactor] mapper에 deleted 값 추가

---

src/main/java/com/kusitms/samsion/domain/comment/domain/repository/CommentRepository.java
src/main/java/com/kusitms/samsion/domain/comment/domain/service/CommentQueryService.java

---
* 댓글 수 반환시 삭제된 댓글까지 포함해서 카운트하는 오류 수정
---
---

[fix] 댓글 수 반환시 삭제된 댓글까지 포함해서 카운트하는 오류 수정

---

src/main/java/com/kusitms/samsion/domain/album/infrastructure/AlbumRepositoryImpl.java
src/main/java/com/kusitms/samsion/domain/comment/domain/entity/Comment.java
src/main/java/com/kusitms/samsion/domain/comment/presentation/CommentController.java
src/main/java/com/kusitms/samsion/domain/grid/application/handler/GridUpdateHandler.java
src/main/java/com/kusitms/samsion/domain/grid/application/service/StampGetUseCase.java
src/main/java/com/kusitms/samsion/domain/grid/domain/entity/Grid.java
src/main/java/com/kusitms/samsion/domain/user/application/handler/UserSignUpHandler.java
src/main/java/com/kusitms/samsion/domain/user/domain/service/UserSaveService.java
src/test/java/com/kusitms/samsion/domain/user/application/handler/UserSignUpHandlerTest.java

---
* 사용자 회원가입시 Grid 생성하도록 수정
---
---

[fix] 사용자 회원가입시 Grid 생성하도록 수정

---

src/docs/asciidoc/Grid-API.adoc
src/docs/asciidoc/index.adoc
src/main/resources/static/docs/Album-API.html
src/main/resources/static/docs/Comment-API.html
src/main/resources/static/docs/Empathy-API.html
src/main/resources/static/docs/FuneralShop-API.html
src/main/resources/static/docs/Grid-API.html
src/main/resources/static/docs/Overview.html
src/main/resources/static/docs/Question-API.html
src/main/resources/static/docs/User-API.html
src/main/resources/static/docs/index.html
src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/domain/grid/presentation/GridControllerTest.java

[feat] 그리드 API 문서 작성

---

src/main/java/com/kusitms/samsion/common/security/oauth/OAuth2SuccessHandler.java

[fix] 소셜 로그인 성고시 redirect url 수정

---

src/main/java/com/kusitms/samsion/domain/comment/application/service/CommentReadUseCase.java

[refactor] 대댓글 하나만 받아와지는 문제 해결

---

src/main/java/com/kusitms/samsion/domain/comment/application/mapper/CommentMapper.java

[refactor] 사용자 프로필 사진으로 변경

---

src/test/java/com/kusitms/samsion/common/consts/TestConst.java
src/test/java/com/kusitms/samsion/common/util/GridCountTrackerTestUtils.java
src/test/java/com/kusitms/samsion/common/util/GridTestUtils.java
src/test/java/com/kusitms/samsion/domain/grid/application/service/GridGetUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/grid/application/service/StampGetUseCaseTest.java
src/test/java/com/kusitms/samsion/domain/grid/domain/service/GridCountTrackerQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/grid/domain/service/GridCountTrackerSaveServiceTest.java
src/test/java/com/kusitms/samsion/domain/grid/domain/service/GridQueryServiceTest.java
src/test/java/com/kusitms/samsion/domain/grid/domain/service/GridSaveServiceTest.java

[feat] 그리드 테스트 코드 작성

---

src/main/java/com/kusitms/samsion/common/infrastructure/s3/S3UploadService.java
src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java

[fix] 사용자 정보 수정시 이미지 미등록시 업데이드 안되게 수정

---

src/main/java/com/kusitms/samsion/domain/user/domain/entity/MyPet.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/User.java

[fix] 사용자 정보 수정시 공백 확인후 수정하도록 수정

---

src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/MyPet.java

[fix] mypet 정보 수정시 공백 확인후 수정하도록 수정

---

src/main/java/com/kusitms/samsion/domain/user/application/dto/request/MyPetUpdateRequest.java
src/main/java/com/kusitms/samsion/domain/user/domain/entity/MyPet.java

[Fix] mypet petAge 값에 0보다 큰 숫자 이외의 값이 입력되면 반영 안되도록 수정
